/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 bugati.gltf 
Author: Joe Jobson (https://sketchfab.com/jjobson98)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bugatti-veyron-dcd46c60fcc9416e8750aed2e04f7071
Title: Bugatti Veyron
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/bugati.gltf')
  return (
    <group {...props} dispose={null} scale={0.35} rotation={[0.27,-1,0]} position={[4.5,0,0]}>
      <group position={[-0.01, -0.03, 0]} rotation={[-Math.PI / 2, 0.006, 0]}>
        <group position={[-11.298, -11.099, -2.179]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.blinn1SG} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.blinn2SG} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.blinn2SG} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.blinn2SG} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.blinn2SG} />
          <mesh geometry={nodes.Object_16.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_36.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_37.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_39.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_43.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_45.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.blinn3SG} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.blinn4SG} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.blinn5SG} />
          <mesh geometry={nodes.Object_49.geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes.Object_51.geometry} material={materials.lambert2SG} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.lambert2SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bugati.gltf')
