/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 freeconcept11.gltf 
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-concept-car-011-public-domain-cc0-099f72bca4494ef9af317e8d76cd99af
Title: FREE Concept Car 011  - public domain (CC0)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/freeconcept11.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} rotation={[0.4,-1.25,0]} scale={0.023} position={[-1.6,-0.6,0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="0046b1e27a1d41b08f4c782ab4229421fbx" rotation={[Math.PI / 2, 0, 0]} >
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_369">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_371" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_373" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_375" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_377" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_379" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_381" position={[69.632, 62.498, -250.817]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                    <group name="Object_383" position={[70.42, 42.417, -242.625]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                    <group name="Object_385" position={[66.208, 59.494, -169.436]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                    <group name="Object_387" position={[70.287, 34.003, -188.73]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                    <group name="Object_389" position={[68.057, 54.034, -210.425]} rotation={[-1.317, -0.18, 0]} scale={100} />
                    <group name="Object_393" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_395" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_397" position={[82.862, 59.693, -159.224]} rotation={[-1.426, 0.057, 1.941]} scale={100} />
                    <group name="Object_399" position={[81.671, 30.675, -163.097]} rotation={[-1.406, 0.057, 1.59]} scale={100} />
                    <group name="Object_401" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_403" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_405" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_407" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_409" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_411" position={[-69.595, 62.498, -250.817]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_413" position={[-70.425, 42.417, -242.625]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_415" position={[-66.129, 59.494, -169.436]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_417" position={[-70.272, 34.003, -188.73]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_419" position={[-68.084, 54.034, -210.425]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_423" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_425" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                    <group name="Object_427" position={[-82.83, 59.621, -159.224]} rotation={[-1.716, 0.054, -1.927]} scale={100} />
                    <group name="Object_429" position={[-81.708, 30.675, -163.097]} rotation={[-1.736, -0.006, -1.552]} scale={100} />
                    <group name="Object_431" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_433" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_435" position={[86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_437" position={[86.105, 30.728, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_439" position={[-86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_441" position={[-86.105, 30.728, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_443" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_445" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_447" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_449" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_451" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_453" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_455" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_457" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_459" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_461" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_463" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_465" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_467" position={[0, 0, -214.595]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_469" position={[0, 0, -214.595]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_471" position={[78.865, 47.617, -255.092]} rotation={[-1.814, 0, 0]} scale={100} />
                    <group name="Object_473" position={[-78.64, 47.617, -255.092]} rotation={[-1.814, 0, 0]} scale={100} />
                    <skinnedMesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_372.skeleton} />
                    <skinnedMesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_374.skeleton} />
                    <skinnedMesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials.chrome_2} skeleton={nodes.Object_376.skeleton} />
                    <skinnedMesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials.blocker} skeleton={nodes.Object_378.skeleton} />
                    <skinnedMesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials.pattern_2_1} skeleton={nodes.Object_380.skeleton} />
                    <skinnedMesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_382.skeleton} />
                    <skinnedMesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_384.skeleton} />
                    <skinnedMesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_386.skeleton} />
                    <skinnedMesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_388.skeleton} />
                    <skinnedMesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_390.skeleton} />
                    <skinnedMesh name="Object_391" geometry={nodes.Object_391.geometry} material={materials.light001} skeleton={nodes.Object_391.skeleton} />
                    <skinnedMesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials.blocker} skeleton={nodes.Object_392.skeleton} />
                    <skinnedMesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials.plastic_matte_2} skeleton={nodes.Object_394.skeleton} />
                    <skinnedMesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_396.skeleton} />
                    <skinnedMesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_398.skeleton} />
                    <skinnedMesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_400.skeleton} />
                    <skinnedMesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_402.skeleton} />
                    <skinnedMesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_404.skeleton} />
                    <skinnedMesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials.chrome_2} skeleton={nodes.Object_406.skeleton} />
                    <skinnedMesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials.blocker} skeleton={nodes.Object_408.skeleton} />
                    <skinnedMesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials.pattern_2_1} skeleton={nodes.Object_410.skeleton} />
                    <skinnedMesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_412.skeleton} />
                    <skinnedMesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_414.skeleton} />
                    <skinnedMesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_416.skeleton} />
                    <skinnedMesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_418.skeleton} />
                    <skinnedMesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_420.skeleton} />
                    <skinnedMesh name="Object_421" geometry={nodes.Object_421.geometry} material={materials.light001} skeleton={nodes.Object_421.skeleton} />
                    <skinnedMesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials.blocker} skeleton={nodes.Object_422.skeleton} />
                    <skinnedMesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials.plastic_matte_2} skeleton={nodes.Object_424.skeleton} />
                    <skinnedMesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_426.skeleton} />
                    <skinnedMesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_428.skeleton} />
                    <skinnedMesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials.metal_dark_2} skeleton={nodes.Object_430.skeleton} />
                    <skinnedMesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_432.skeleton} />
                    <skinnedMesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_434.skeleton} />
                    <skinnedMesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials.metal_1} skeleton={nodes.Object_436.skeleton} />
                    <skinnedMesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials.metal_1} skeleton={nodes.Object_438.skeleton} />
                    <skinnedMesh name="Object_440" geometry={nodes.Object_440.geometry} material={materials.metal_1} skeleton={nodes.Object_440.skeleton} />
                    <skinnedMesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials.metal_1} skeleton={nodes.Object_442.skeleton} />
                    <skinnedMesh name="Object_444" geometry={nodes.Object_444.geometry} material={materials.body} skeleton={nodes.Object_444.skeleton} />
                    <skinnedMesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials.body} skeleton={nodes.Object_446.skeleton} />
                    <skinnedMesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials.plastic_matte_3} skeleton={nodes.Object_448.skeleton} />
                    <skinnedMesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials.chrome} skeleton={nodes.Object_450.skeleton} />
                    <skinnedMesh name="Object_452" geometry={nodes.Object_452.geometry} material={materials.glass} skeleton={nodes.Object_452.skeleton} />
                    <skinnedMesh name="Object_454" geometry={nodes.Object_454.geometry} material={materials.plastic_matte_3} skeleton={nodes.Object_454.skeleton} />
                    <skinnedMesh name="Object_456" geometry={nodes.Object_456.geometry} material={materials.glass} skeleton={nodes.Object_456.skeleton} />
                    <skinnedMesh name="Object_458" geometry={nodes.Object_458.geometry} material={materials.body} skeleton={nodes.Object_458.skeleton} />
                    <skinnedMesh name="Object_460" geometry={nodes.Object_460.geometry} material={materials.plastic_matte_3} skeleton={nodes.Object_460.skeleton} />
                    <skinnedMesh name="Object_462" geometry={nodes.Object_462.geometry} material={materials.body} skeleton={nodes.Object_462.skeleton} />
                    <skinnedMesh name="Object_464" geometry={nodes.Object_464.geometry} material={materials.plastic_matte_3} skeleton={nodes.Object_464.skeleton} />
                    <skinnedMesh name="Object_466" geometry={nodes.Object_466.geometry} material={materials.chrome} skeleton={nodes.Object_466.skeleton} />
                    <skinnedMesh name="Object_468" geometry={nodes.Object_468.geometry} material={materials.blockers} skeleton={nodes.Object_468.skeleton} />
                    <skinnedMesh name="Object_470" geometry={nodes.Object_470.geometry} material={materials.blockers} skeleton={nodes.Object_470.skeleton} />
                    <skinnedMesh name="Object_472" geometry={nodes.Object_472.geometry} material={materials.metal_1} skeleton={nodes.Object_472.skeleton} />
                    <skinnedMesh name="Object_474" geometry={nodes.Object_474.geometry} material={materials.metal_1} skeleton={nodes.Object_474.skeleton} />
                  </group>
                </group>
                <group name="Empty_frontWheels" position={[0, 37.89, -108.783]} rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <group name="Empty_FL_Wheels" position={[0.837, 0, 0]}>
                    <group name="wheelCON_v006_Coll">
                      <group name="wheelCON_v006_Coll|Plane005|Dupli|">
                        <mesh name="wheelCON_v006_Coll|Plane005|Dupli|_rims001_0" geometry={nodes['wheelCON_v006_Coll|Plane005|Dupli|_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll|Plane004|Dupli|1" position={[-0.01, 0, 0]} scale={0.973}>
                        <mesh name="wheelCON_v006_Coll|Plane004|Dupli|1_rims001_0" geometry={nodes['wheelCON_v006_Coll|Plane004|Dupli|1_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll|Cube015|Dupli|2" position={[-0.01, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll|Cube015|Dupli|2_rims001_0" geometry={nodes['wheelCON_v006_Coll|Cube015|Dupli|2_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll|Cube016|Dupli|3" position={[-0.01, 0, 0]} rotation={[-1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll|Cube016|Dupli|3_rims001_0" geometry={nodes['wheelCON_v006_Coll|Cube016|Dupli|3_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll|Cube017|Dupli|4" position={[-0.01, 0, 0]} rotation={[1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll|Cube017|Dupli|4_rims001_0" geometry={nodes['wheelCON_v006_Coll|Cube017|Dupli|4_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll|Cube018|Dupli|5" position={[-0.01, 0, 0]} rotation={[2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll|Cube018|Dupli|5_rims001_0" geometry={nodes['wheelCON_v006_Coll|Cube018|Dupli|5_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll|Cube019|Dupli|6" position={[-0.01, 0, 0]} rotation={[-2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll|Cube019|Dupli|6_rims001_0" geometry={nodes['wheelCON_v006_Coll|Cube019|Dupli|6_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                    </group>
                    <group name="tire_v001_Coll">
                      <group name="tire_v001_Coll|Mesh5004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="tire_v001_Coll|Mesh5004|Dupli|_rubber___tires001_0" geometry={nodes['tire_v001_Coll|Mesh5004|Dupli|_rubber___tires001_0'].geometry} material={materials['rubber___tires.001']} />
                        <mesh name="tire_v001_Coll|Mesh5004|Dupli|_tireProtector_0" geometry={nodes['tire_v001_Coll|Mesh5004|Dupli|_tireProtector_0'].geometry} material={materials.tireProtector} />
                      </group>
                    </group>
                    <group name="brakes_Coll">
                      <group name="brakes_Coll|Mesh6004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll|Mesh6004|Dupli|_brakeCalipers_0" geometry={nodes['brakes_Coll|Mesh6004|Dupli|_brakeCalipers_0'].geometry} material={materials.brakeCalipers} />
                      </group>
                      <group name="brakes_Coll|Mesh7004|Dupli|1" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll|Mesh7004|Dupli|1_metal_1001_0" geometry={nodes['brakes_Coll|Mesh7004|Dupli|1_metal_1001_0'].geometry} material={materials['metal_1.001']} />
                      </group>
                    </group>
                    <group name="tire_v001_Coll001" position={[-1.676, 0, 0]} rotation={[0, 0, Math.PI]}>
                      <group name="tire_v001_Coll001|Mesh5004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="tire_v001_Coll001|Mesh5004|Dupli|_rubber___tires001_0" geometry={nodes['tire_v001_Coll001|Mesh5004|Dupli|_rubber___tires001_0'].geometry} material={materials['rubber___tires.001']} />
                        <mesh name="tire_v001_Coll001|Mesh5004|Dupli|_tireProtector_0" geometry={nodes['tire_v001_Coll001|Mesh5004|Dupli|_tireProtector_0'].geometry} material={materials.tireProtector} />
                      </group>
                    </group>
                    <group name="tire_v001_Coll003" position={[-1.676, 2.145, 0]} rotation={[0, 0, Math.PI]}>
                      <group name="tire_v001_Coll003|Mesh5004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="tire_v001_Coll003|Mesh5004|Dupli|_rubber___tires001_0" geometry={nodes['tire_v001_Coll003|Mesh5004|Dupli|_rubber___tires001_0'].geometry} material={materials['rubber___tires.001']} />
                        <mesh name="tire_v001_Coll003|Mesh5004|Dupli|_tireProtector_0" geometry={nodes['tire_v001_Coll003|Mesh5004|Dupli|_tireProtector_0'].geometry} material={materials.tireProtector} />
                      </group>
                    </group>
                  </group>
                  <group name="Empty_FR_Wheels" position={[-0.839, 0, 0]}>
                    <group name="wheelCON_v006_Coll002" rotation={[-Math.PI, 0, 0]} scale={-1}>
                      <group name="wheelCON_v006_Coll002|Plane005|Dupli|">
                        <mesh name="wheelCON_v006_Coll002|Plane005|Dupli|_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Plane005|Dupli|_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll002|Plane004|Dupli|1" position={[-0.01, 0, 0]} scale={0.973}>
                        <mesh name="wheelCON_v006_Coll002|Plane004|Dupli|1_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Plane004|Dupli|1_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll002|Cube015|Dupli|2" position={[-0.01, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll002|Cube015|Dupli|2_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Cube015|Dupli|2_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll002|Cube016|Dupli|3" position={[-0.01, 0, 0]} rotation={[-1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll002|Cube016|Dupli|3_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Cube016|Dupli|3_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll002|Cube017|Dupli|4" position={[-0.01, 0, 0]} rotation={[1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll002|Cube017|Dupli|4_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Cube017|Dupli|4_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll002|Cube018|Dupli|5" position={[-0.01, 0, 0]} rotation={[2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll002|Cube018|Dupli|5_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Cube018|Dupli|5_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll002|Cube019|Dupli|6" position={[-0.01, 0, 0]} rotation={[-2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll002|Cube019|Dupli|6_rims001_0" geometry={nodes['wheelCON_v006_Coll002|Cube019|Dupli|6_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                    </group>
                    <group name="brakes_Coll001" rotation={[-Math.PI, 0, 0]} scale={-1}>
                      <group name="brakes_Coll001|Mesh6004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll001|Mesh6004|Dupli|_brakeCalipers_0" geometry={nodes['brakes_Coll001|Mesh6004|Dupli|_brakeCalipers_0'].geometry} material={materials.brakeCalipers} />
                      </group>
                      <group name="brakes_Coll001|Mesh7004|Dupli|1" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll001|Mesh7004|Dupli|1_metal_1001_0" geometry={nodes['brakes_Coll001|Mesh7004|Dupli|1_metal_1001_0'].geometry} material={materials['metal_1.001']} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="Empty_rearWheels" position={[0, 37.89, -353.275]} rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <group name="Empty_FL_Wheels001" position={[0.837, 0, 0]}>
                    <group name="wheelCON_v006_Coll001">
                      <group name="wheelCON_v006_Coll001|Plane005|Dupli|">
                        <mesh name="wheelCON_v006_Coll001|Plane005|Dupli|_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Plane005|Dupli|_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll001|Plane004|Dupli|1" position={[-0.01, 0, 0]} scale={0.973}>
                        <mesh name="wheelCON_v006_Coll001|Plane004|Dupli|1_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Plane004|Dupli|1_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll001|Cube015|Dupli|2" position={[-0.01, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll001|Cube015|Dupli|2_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Cube015|Dupli|2_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll001|Cube016|Dupli|3" position={[-0.01, 0, 0]} rotation={[-1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll001|Cube016|Dupli|3_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Cube016|Dupli|3_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll001|Cube017|Dupli|4" position={[-0.01, 0, 0]} rotation={[1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll001|Cube017|Dupli|4_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Cube017|Dupli|4_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll001|Cube018|Dupli|5" position={[-0.01, 0, 0]} rotation={[2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll001|Cube018|Dupli|5_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Cube018|Dupli|5_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll001|Cube019|Dupli|6" position={[-0.01, 0, 0]} rotation={[-2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll001|Cube019|Dupli|6_rims001_0" geometry={nodes['wheelCON_v006_Coll001|Cube019|Dupli|6_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                    </group>
                    <group name="tire_v001_Coll002">
                      <group name="tire_v001_Coll002|Mesh5004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="tire_v001_Coll002|Mesh5004|Dupli|_rubber___tires001_0" geometry={nodes['tire_v001_Coll002|Mesh5004|Dupli|_rubber___tires001_0'].geometry} material={materials['rubber___tires.001']} />
                        <mesh name="tire_v001_Coll002|Mesh5004|Dupli|_tireProtector_0" geometry={nodes['tire_v001_Coll002|Mesh5004|Dupli|_tireProtector_0'].geometry} material={materials.tireProtector} />
                      </group>
                    </group>
                    <group name="brakes_Coll002">
                      <group name="brakes_Coll002|Mesh6004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll002|Mesh6004|Dupli|_brakeCalipers_0" geometry={nodes['brakes_Coll002|Mesh6004|Dupli|_brakeCalipers_0'].geometry} material={materials.brakeCalipers} />
                      </group>
                      <group name="brakes_Coll002|Mesh7004|Dupli|1" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll002|Mesh7004|Dupli|1_metal_1001_0" geometry={nodes['brakes_Coll002|Mesh7004|Dupli|1_metal_1001_0'].geometry} material={materials['metal_1.001']} />
                      </group>
                    </group>
                  </group>
                  <group name="Empty_FR_Wheels001" position={[-0.839, 0, 0]}>
                    <group name="wheelCON_v006_Coll003" rotation={[-Math.PI, 0, 0]} scale={-1}>
                      <group name="wheelCON_v006_Coll003|Plane005|Dupli|">
                        <mesh name="wheelCON_v006_Coll003|Plane005|Dupli|_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Plane005|Dupli|_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll003|Plane004|Dupli|1" position={[-0.01, 0, 0]} scale={0.973}>
                        <mesh name="wheelCON_v006_Coll003|Plane004|Dupli|1_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Plane004|Dupli|1_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll003|Cube015|Dupli|2" position={[-0.01, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll003|Cube015|Dupli|2_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Cube015|Dupli|2_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll003|Cube016|Dupli|3" position={[-0.01, 0, 0]} rotation={[-1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll003|Cube016|Dupli|3_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Cube016|Dupli|3_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll003|Cube017|Dupli|4" position={[-0.01, 0, 0]} rotation={[1.257, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll003|Cube017|Dupli|4_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Cube017|Dupli|4_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll003|Cube018|Dupli|5" position={[-0.01, 0, 0]} rotation={[2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll003|Cube018|Dupli|5_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Cube018|Dupli|5_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                      <group name="wheelCON_v006_Coll003|Cube019|Dupli|6" position={[-0.01, 0, 0]} rotation={[-2.513, 0, 0]} scale={0.343}>
                        <mesh name="wheelCON_v006_Coll003|Cube019|Dupli|6_rims001_0" geometry={nodes['wheelCON_v006_Coll003|Cube019|Dupli|6_rims001_0'].geometry} material={materials['rims.001']} />
                      </group>
                    </group>
                    <group name="brakes_Coll003" rotation={[-Math.PI, 0, 0]} scale={-1}>
                      <group name="brakes_Coll003|Mesh6004|Dupli|" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll003|Mesh6004|Dupli|_brakeCalipers_0" geometry={nodes['brakes_Coll003|Mesh6004|Dupli|_brakeCalipers_0'].geometry} material={materials.brakeCalipers} />
                      </group>
                      <group name="brakes_Coll003|Mesh7004|Dupli|1" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
                        <mesh name="brakes_Coll003|Mesh7004|Dupli|1_metal_1001_0" geometry={nodes['brakes_Coll003|Mesh7004|Dupli|1_metal_1001_0'].geometry} material={materials['metal_1.001']} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="wheel_cover001" position={[95.404, 37.89, -108.783]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="wheel_cover001|wheel_cover|Dupli|">
                    <mesh name="wheel_cover001|wheel_cover|Dupli|_metal_dark_2_0" geometry={nodes['wheel_cover001|wheel_cover|Dupli|_metal_dark_2_0'].geometry} material={materials.metal_dark_2} />
                  </group>
                </group>
                <group name="wheel_cover002" position={[95.404, 37.89, -353.275]} rotation={[-2.967, 0, 0]} scale={100}>
                  <group name="wheel_cover002|wheel_cover|Dupli|">
                    <mesh name="wheel_cover002|wheel_cover|Dupli|_metal_dark_2_0" geometry={nodes['wheel_cover002|wheel_cover|Dupli|_metal_dark_2_0'].geometry} material={materials.metal_dark_2} />
                  </group>
                </group>
                <group name="wheel_cover003" position={[-95.606, 37.89, -108.783]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100}>
                  <group name="wheel_cover003|wheel_cover|Dupli|">
                    <mesh name="wheel_cover003|wheel_cover|Dupli|_metal_dark_2_0" geometry={nodes['wheel_cover003|wheel_cover|Dupli|_metal_dark_2_0'].geometry} material={materials.metal_dark_2} />
                  </group>
                </group>
                <group name="wheel_cover004" position={[-95.606, 37.89, -353.275]} rotation={[-2.618, 0, -Math.PI]} scale={100}>
                  <group name="wheel_cover004|wheel_cover|Dupli|">
                    <mesh name="wheel_cover004|wheel_cover|Dupli|_metal_dark_2_0" geometry={nodes['wheel_cover004|wheel_cover|Dupli|_metal_dark_2_0'].geometry} material={materials.metal_dark_2} />
                  </group>
                </group>
                <group name="SW_Empty" position={[32.207, 78.056, -202.259]} rotation={[-1.222, 0, 0]} scale={100}>
                  <group name="Cube078">
                    <mesh name="Cube078_plastic_smooth_0" geometry={nodes.Cube078_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Cube079">
                    <mesh name="Cube079_chrome_2_0" geometry={nodes.Cube079_chrome_2_0.geometry} material={materials.chrome_2} />
                  </group>
                  <group name="Cube080">
                    <mesh name="Cube080_pattern_2_1_0" geometry={nodes.Cube080_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                  </group>
                  <group name="Torus003">
                    <mesh name="Torus003_plastic_smooth_0" geometry={nodes.Torus003_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Torus007">
                    <mesh name="Torus007_chrome_2_0" geometry={nodes.Torus007_chrome_2_0.geometry} material={materials.chrome_2} />
                  </group>
                  <group name="Torus008">
                    <mesh name="Torus008_pattern_2_1_0" geometry={nodes.Torus008_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                  </group>
                  <group name="SW_base">
                    <mesh name="SW_base_plastic_smooth_0" geometry={nodes.SW_base_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                    <mesh name="SW_base_blocker_0" geometry={nodes.SW_base_blocker_0.geometry} material={materials.blocker} />
                  </group>
                  <group name="Cube072" position={[0.072, -0.292, -0.013]}>
                    <mesh name="Cube072_plastic_smooth_0" geometry={nodes.Cube072_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Cube073" position={[-0.07, -0.292, -0.013]} rotation={[-Math.PI, 0, 0]}>
                    <mesh name="Cube073_plastic_smooth_0" geometry={nodes.Cube073_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Empty044" position={[0, -0.489, 0.038]}>
                    <group name="Empty045" position={[0, 0.312, 0.159]}>
                      <group name="Text" position={[-0.01, 0, -0.028]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.907}>
                        <mesh name="Text_light001_0" geometry={nodes.Text_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Text004" position={[-0.013, 0, -0.018]} rotation={[-Math.PI / 2, 0, -Math.PI]}>
                        <mesh name="Text004_light001_0" geometry={nodes.Text004_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Text005" position={[0.055, 0, -0.029]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.603}>
                        <mesh name="Text005_light001_0" geometry={nodes.Text005_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Cube091" position={[0, -0.001, -0.127]}>
                        <mesh name="Cube091_light001_0" geometry={nodes.Cube091_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Cube092" position={[0.047, 0, 0.003]}>
                        <group name="Cube093" position={[0, 0, -0.026]}>
                          <mesh name="Cube093_light001_0" geometry={nodes.Cube093_light001_0.geometry} material={materials.light001} />
                        </group>
                        <mesh name="Cube092_light001_0" geometry={nodes.Cube092_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Text006" position={[0.096, 0, -0.029]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.8}>
                        <mesh name="Text006_light001_0" geometry={nodes.Text006_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Cube094" position={[0.079, 0, 0.003]}>
                        <group name="Cube095" position={[0, 0, -0.026]}>
                          <mesh name="Cube095_light001_0" geometry={nodes.Cube095_light001_0.geometry} material={materials.light001} />
                        </group>
                        <group name="Cube096" position={[0, 0, -0.026]}>
                          <mesh name="Cube096_light001_0" geometry={nodes.Cube096_light001_0.geometry} material={materials.light001} />
                        </group>
                        <mesh name="Cube094_light001_0" geometry={nodes.Cube094_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Text007" position={[0.114, 0, -0.029]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.8}>
                        <mesh name="Text007_light001_0" geometry={nodes.Text007_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Cube097" position={[0.11, 0, 0.003]}>
                        <group name="Cube098" position={[0, 0, -0.026]}>
                          <mesh name="Cube098_light001_0" geometry={nodes.Cube098_light001_0.geometry} material={materials.light001} />
                        </group>
                        <group name="Cube099" position={[0, 0, -0.026]}>
                          <mesh name="Cube099_light001_0" geometry={nodes.Cube099_light001_0.geometry} material={materials.light001} />
                        </group>
                        <mesh name="Cube097_light001_0" geometry={nodes.Cube097_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Text008" position={[-0.101, 0, -0.029]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={0.8}>
                        <mesh name="Text008_light001_0" geometry={nodes.Text008_light001_0.geometry} material={materials.light001} />
                      </group>
                      <group name="Cube100" position={[-0.118, 0, 0.003]}>
                        <group name="Cube101" position={[0, 0, -0.026]}>
                          <mesh name="Cube101_light001_0" geometry={nodes.Cube101_light001_0.geometry} material={materials.light001} />
                        </group>
                        <group name="Cube102" position={[0, 0, -0.026]}>
                          <mesh name="Cube102_light001_0" geometry={nodes.Cube102_light001_0.geometry} material={materials.light001} />
                        </group>
                        <mesh name="Cube100_light001_0" geometry={nodes.Cube100_light001_0.geometry} material={materials.light001} />
                      </group>
                    </group>
                    <group name="Cube087" position={[0, 0.312, 0.031]}>
                      <mesh name="Cube087_blockerBlackHole_0" geometry={nodes.Cube087_blockerBlackHole_0.geometry} material={materials.blockerBlackHole} />
                    </group>
                    <group name="SW_base001" position={[0, 0.489, -0.038]}>
                      <mesh name="SW_base001_plastic_smooth_0" geometry={nodes.SW_base001_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                    </group>
                    <group name="SW_base002" position={[0, 0.489, -0.038]}>
                      <mesh name="SW_base002_plastic_smooth_0" geometry={nodes.SW_base002_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                    </group>
                  </group>
                </group>
                <group name="door_maps_Empty" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100}>
                  <group name="Cube054" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube056" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube057" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube058" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube059" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="nut012" position={[69.632, 62.498, -250.817]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                  <group name="nut013" position={[70.42, 42.417, -242.625]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                  <group name="nut014" position={[66.208, 59.494, -169.436]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                  <group name="nut015" position={[70.287, 34.003, -188.73]} rotation={[-1.416, 0, Math.PI / 2]} scale={100} />
                  <group name="Cube060" position={[68.057, 54.034, -210.425]} rotation={[-1.317, -0.18, 0]} scale={100} />
                  <group name="Cube061" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube062" position={[69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="nut030" position={[82.862, 59.693, -159.224]} rotation={[-1.426, 0.057, 1.941]} scale={100} />
                  <group name="nut031" position={[81.671, 30.675, -163.097]} rotation={[-1.406, 0.057, 1.59]} scale={100} />
                </group>
                <group name="door_maps_Empty001" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100}>
                  <group name="Cube109" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube111" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube112" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube113" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube114" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="nut032" position={[-69.595, 62.498, -250.817]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                  <group name="nut033" position={[-70.425, 42.417, -242.625]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                  <group name="nut034" position={[-66.129, 59.494, -169.436]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                  <group name="nut035" position={[-70.272, 34.003, -188.73]} rotation={[-1.726, 0, -Math.PI / 2]} scale={100} />
                  <group name="Cube115" position={[-68.084, 54.034, -210.425]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube116" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="Cube117" position={[-69.905, 51.226, -213.491]} rotation={[-1.416, 0, 0]} scale={100} />
                  <group name="nut036" position={[-82.83, 59.621, -159.224]} rotation={[-1.716, 0.054, -1.927]} scale={100} />
                  <group name="nut037" position={[-81.708, 30.675, -163.097]} rotation={[-1.736, -0.006, -1.552]} scale={100} />
                </group>
                <group name="seats_Empty" position={[32.195, -4.825, -215.205]} rotation={[-1.661, 0, 0]} scale={100}>
                  <group name="Plane102">
                    <mesh name="Plane102_plastic_smooth_0" geometry={nodes.Plane102_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Plane103">
                    <mesh name="Plane103_plastic_smooth_0" geometry={nodes.Plane103_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Plane104">
                    <mesh name="Plane104_plastic_matte_0" geometry={nodes.Plane104_plastic_matte_0.geometry} material={materials.plastic_matte} />
                  </group>
                  <group name="nut008" position={[0.126, 0.34, 0.422]}>
                    <mesh name="nut008_metal_dark_0" geometry={nodes.nut008_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="Plane105">
                    <mesh name="Plane105_pattern_2_1_0" geometry={nodes.Plane105_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                  </group>
                  <group name="Plane106">
                    <mesh name="Plane106_pattern_2_1_0" geometry={nodes.Plane106_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                  </group>
                  <group name="nut009" position={[-0.126, 0.34, 0.422]}>
                    <mesh name="nut009_metal_dark_0" geometry={nodes.nut009_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="Plane107">
                    <mesh name="Plane107_plastic_smooth_0" geometry={nodes.Plane107_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Plane108">
                    <mesh name="Plane108_plastic_smooth_0" geometry={nodes.Plane108_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="nut010" position={[0.166, 0.229, 0.184]}>
                    <mesh name="nut010_metal_dark_0" geometry={nodes.nut010_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="nut011" position={[-0.165, 0.229, 0.184]}>
                    <mesh name="nut011_metal_dark_0" geometry={nodes.nut011_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="main_outline">
                    <mesh name="main_outline_blocker_0" geometry={nodes.main_outline_blocker_0.geometry} material={materials.blocker} />
                  </group>
                </group>
                <group name="seats_Empty001" position={[-32.112, -4.825, -215.205]} rotation={[-1.661, 0, 0]} scale={100}>
                  <group name="Plane115">
                    <mesh name="Plane115_plastic_smooth_0" geometry={nodes.Plane115_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Plane116">
                    <mesh name="Plane116_plastic_smooth_0" geometry={nodes.Plane116_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Plane117">
                    <mesh name="Plane117_plastic_matte_0" geometry={nodes.Plane117_plastic_matte_0.geometry} material={materials.plastic_matte} />
                  </group>
                  <group name="nut017" position={[0.126, 0.34, 0.422]}>
                    <mesh name="nut017_metal_dark_0" geometry={nodes.nut017_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="Plane118">
                    <mesh name="Plane118_pattern_2_1_0" geometry={nodes.Plane118_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                  </group>
                  <group name="Plane119">
                    <mesh name="Plane119_pattern_2_1_0" geometry={nodes.Plane119_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                  </group>
                  <group name="nut018" position={[-0.126, 0.34, 0.422]}>
                    <mesh name="nut018_metal_dark_0" geometry={nodes.nut018_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="Plane120">
                    <mesh name="Plane120_plastic_smooth_0" geometry={nodes.Plane120_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="Plane121">
                    <mesh name="Plane121_plastic_smooth_0" geometry={nodes.Plane121_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                  </group>
                  <group name="nut020" position={[0.166, 0.229, 0.184]}>
                    <mesh name="nut020_metal_dark_0" geometry={nodes.nut020_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="nut021" position={[-0.165, 0.229, 0.184]}>
                    <mesh name="nut021_metal_dark_0" geometry={nodes.nut021_metal_dark_0.geometry} material={materials.metal_dark} />
                  </group>
                  <group name="main_outline001">
                    <mesh name="main_outline001_blocker_0" geometry={nodes.main_outline001_blocker_0.geometry} material={materials.blocker} />
                  </group>
                </group>
                <group name="Plane110" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane110_plastic_smooth_0" geometry={nodes.Plane110_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                </group>
                <group name="Plane111" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane123" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane123_plastic_smooth_0" geometry={nodes.Plane123_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                </group>
                <group name="Plane124" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane124_pattern_2_1_0" geometry={nodes.Plane124_pattern_2_1_0.geometry} material={materials.pattern_2_1} />
                </group>
                <group name="Plane125" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane125_plastic_smooth_0" geometry={nodes.Plane125_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                </group>
                <group name="Plane126" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane126_blockerBlackHole_0" geometry={nodes.Plane126_blockerBlackHole_0.geometry} material={materials.blockerBlackHole} />
                </group>
                <group name="Plane127" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane127_floorMat_0" geometry={nodes.Plane127_floorMat_0.geometry} material={materials.floorMat} />
                </group>
                <group name="Plane128" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane128_floorMat_0" geometry={nodes.Plane128_floorMat_0.geometry} material={materials.floorMat} />
                </group>
                <group name="Plane129" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane129_chrome_0" geometry={nodes.Plane129_chrome_0.geometry} material={materials.chrome} />
                </group>
                <group name="Plane130" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Plane130_plastic_smooth_0" geometry={nodes.Plane130_plastic_smooth_0.geometry} material={materials.plastic_smooth} />
                </group>
                <group name="Plane131" position={[0, 22, -210.772]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane132" position={[19.697, 17.589, -152.844]} rotation={[-1.74, 0, 0]} scale={100}>
                  <mesh name="Plane132_Metal_3_0" geometry={nodes.Plane132_Metal_3_0.geometry} material={materials.Metal_3} />
                </group>
                <group name="Plane133" position={[34.808, 26.382, -147.024]} rotation={[-1.444, 0, 0]} scale={100}>
                  <mesh name="Plane133_Metal_3_0" geometry={nodes.Plane133_Metal_3_0.geometry} material={materials.Metal_3} />
                </group>
                <group name="Plane134" position={[34.812, 18.272, -156.561]} rotation={[-1.444, 0, 0]} scale={100}>
                  <mesh name="Plane134_metal_dark_0" geometry={nodes.Plane134_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Plane135" position={[19.56, 17.589, -152.844]} rotation={[-1.583, 0, 0]} scale={100}>
                  <mesh name="Plane135_metal_dark_0" geometry={nodes.Plane135_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Cylinder006" position={[86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder007" position={[86.105, 30.728, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder009" position={[86.105, 30.728, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder009_metal_1_0" geometry={nodes.Cylinder009_metal_1_0.geometry} material={materials.metal_1} />
                </group>
                <group name="Cylinder008" position={[86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder008_metal_1_0" geometry={nodes.Cylinder008_metal_1_0.geometry} material={materials.metal_1} />
                </group>
                <group name="Cylinder011" position={[-86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder012" position={[-86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder012_metal_1_0" geometry={nodes.Cylinder012_metal_1_0.geometry} material={materials.metal_1} />
                </group>
                <group name="Cylinder013" position={[-86.105, 30.728, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder014" position={[-86.105, 30.728, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder014_metal_1_0" geometry={nodes.Cylinder014_metal_1_0.geometry} material={materials.metal_1} />
                </group>
                <group name="Text009" position={[3.79, 82.06, -126.135]} rotation={[-2.932, 0, -Math.PI]} scale={37.06}>
                  <mesh name="Text009_light001_0" geometry={nodes.Text009_light001_0.geometry} material={materials.light001} />
                </group>
                <group name="Cube020" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube021" rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube021_chrome_0" geometry={nodes.Cube021_chrome_0.geometry} material={materials.chrome} />
                </group>
                <group name="Cube022" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube022_taillight_cover_0" geometry={nodes.Cube022_taillight_cover_0.geometry} material={materials.taillight_cover} />
                </group>
                <group name="Cube023" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube023_glass_0" geometry={nodes.Cube023_glass_0.geometry} material={materials.glass} />
                </group>
                <group name="Cube024" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube024_glass_0" geometry={nodes.Cube024_glass_0.geometry} material={materials.glass} />
                </group>
                <group name="Cube025" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube025_body_0" geometry={nodes.Cube025_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube026" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube026_body_0" geometry={nodes.Cube026_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube027" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube027_body_0" geometry={nodes.Cube027_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube028" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube028_body_0" geometry={nodes.Cube028_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube029" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube029_headlight_cover_0" geometry={nodes.Cube029_headlight_cover_0.geometry} material={materials.headlight_cover} />
                </group>
                <group name="Cube030" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube030_body_0" geometry={nodes.Cube030_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube031" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube031_plastic_matte_3_0" geometry={nodes.Cube031_plastic_matte_3_0.geometry} material={materials.plastic_matte_3} />
                </group>
                <group name="Cube032" rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube032_plastic_matte_3_0" geometry={nodes.Cube032_plastic_matte_3_0.geometry} material={materials.plastic_matte_3} />
                </group>
                <group name="Cube033" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube033_plastic_matte_3_0" geometry={nodes.Cube033_plastic_matte_3_0.geometry} material={materials.plastic_matte_3} />
                </group>
                <group name="Cube034" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube034_body_0" geometry={nodes.Cube034_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube035" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube036" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube037" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube038" position={[0, 0, -214.595]} rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube038_blockers_0" geometry={nodes.Cube038_blockers_0.geometry} material={materials.blockers} />
                </group>
                <group name="Cube039" rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube039_chrome_0" geometry={nodes.Cube039_chrome_0.geometry} material={materials.chrome} />
                </group>
                <group name="Cube040" rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube040_taillight_chrome_0" geometry={nodes.Cube040_taillight_chrome_0.geometry} material={materials.taillight_chrome} />
                </group>
                <group name="Cube047" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube047_body_0" geometry={nodes.Cube047_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube048" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube049" rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube049_plastic_matte_3_0" geometry={nodes.Cube049_plastic_matte_3_0.geometry} material={materials.plastic_matte_3} />
                </group>
                <group name="Cube050" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube051" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube051_body_0" geometry={nodes.Cube051_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube052" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cube052_body_0" geometry={nodes.Cube052_body_0.geometry} material={materials.body} />
                </group>
                <group name="Cube053" rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube053_chrome_0" geometry={nodes.Cube053_chrome_0.geometry} material={materials.chrome} />
                </group>
                <group name="Cube105" position={[0, 0, -214.595]} rotation={[-Math.PI / 2, 0, 0]} scale={113.96}>
                  <mesh name="Cube105_blockers_0" geometry={nodes.Cube105_blockers_0.geometry} material={materials.blockers} />
                </group>
                <group name="Circle" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Circle_blockers_0" geometry={nodes.Circle_blockers_0.geometry} material={materials.blockers} />
                </group>
                <group name="Cube106" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube107" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube108" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube055" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube110" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube118" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube127" position={[0, 0, -214.595]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube128" position={[0, 0, -214.595]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder010" position={[78.865, 47.617, -255.092]} rotation={[-1.814, 0, 0]} scale={100} />
                <group name="Cylinder015" position={[-78.64, 47.617, -255.092]} rotation={[-1.814, 0, 0]} scale={100} />
                <group name="Empty" position={[86.105, 59.65, -151.189]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/freeconcept11.gltf')
