/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 freeconcept3.gltf 
Author: Unity Fan youtube channel (https://sketchfab.com/unityfan777)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/free-concept-car-003-public-domain-cc0-77664fc474c444f4947e9834ed0d30ad
Title: FREE Concept Car 003 - public domain (CC0)
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/freeconcept3.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null} rotation={[0.4,0.6,0]} scale={1.35} position={[1,0,0]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="315a85fe21b74477b50aae6a583d0f87fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_13" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_15" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_17" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_19" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_21" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_23" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_25" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_29" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_31" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_33" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_35" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_37" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_39" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_41" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_43" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_45" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_47" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_51" rotation={[-1.501, 0, 0]} scale={100} />
                    <group name="Object_53" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_55" position={[103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_57" position={[103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_59" position={[103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, Math.PI / 3]} scale={100} />
                    <group name="Object_61" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, Math.PI / 3]} scale={100} />
                    <group name="Object_63" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_65" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_67" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_69" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_71" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_73" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_75" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_77" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_79" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_81" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_83" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_85" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_87" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_89" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_91" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_93" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_95" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_97" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_99" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    {/* <group name="Object_101" position={[-103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_103" position={[-103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_105" position={[-103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, -Math.PI / 3]} scale={100} />
                    <group name="Object_107" position={[-103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_109" position={[-103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_111" position={[-103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, -Math.PI / 3]} scale={100} /> */}
                    <group name="Object_113" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_115" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_117" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_119" rotation={[-1.518, 0, 0]} scale={100} />
                    <group name="Object_121" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_123" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_125" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_129" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_131" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_133" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_135" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_137" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_139" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_141" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_143" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_145" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_147" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_151" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_153" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_155" position={[104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
                    <group name="Object_157" position={[104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_159" position={[104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_161" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_163" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_165" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_167" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_169" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_171" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_173" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_175" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_177" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_179" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_181" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_183" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_185" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_187" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_189" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_191" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_193" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_195" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_197" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_199" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_201" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_203" position={[-104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
                    <group name="Object_205" position={[-104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_207" position={[-104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <group name="Object_209" position={[-104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
                    <group name="Object_211" position={[-104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_213" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_215" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_217" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_219" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_221" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_223" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_225" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_227" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_229" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_231" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_233" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_235" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_237" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_239" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_241" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_243" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_245" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_247" position={[0, 0, 84.93]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_249" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_251" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_253" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_255" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_257" position={[0.075, 133.281, 34.15]} rotation={[-Math.PI / 2, 0, -0.179]} scale={100} />
                    <group name="Object_259" position={[0, 133.281, 34.566]} rotation={[-Math.PI / 2, 0, -0.179]} scale={100} />
                    <group name="Object_261" position={[0, 133.281, 34.566]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_263" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_265" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_267" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_269" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_271" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_273" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_275" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_277" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_279" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_282" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_284" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_286" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_288" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_290" position={[4.576, 90.443, 137.249]} rotation={[-2.836, 0, Math.PI]} scale={50.452} />
                    <group name="Object_292" position={[0.04, 136.798, 32.624]} rotation={[-Math.PI, 0, 0]} scale={100} />
                    <group name="Object_294" position={[-0.001, 137.086, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={[147.416, 147.416, 98.074]} />
                    <group name="Object_296" position={[0, 136.82, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_298" position={[0, 3.363, -11.952]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_300" position={[90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <group name="Object_303" position={[90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <group name="Object_306" position={[-90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <group name="Object_309" position={[-90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                    <group name="Object_312" position={[90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_315" position={[90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_318" position={[-90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_321" position={[-90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_324" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_326" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_328" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_330" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_332" position={[27.235, 80.594, 36.272]} rotation={[-2.793, 0, 0]} scale={100} />
                    <group name="Object_334" position={[27.235, 80.594, 36.272]} rotation={[-2.793, 0, 0]} scale={100} />
                    <group name="Object_336" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_339" position={[34.456, 69.39, 63.318]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_341" position={[20.209, 69.39, 63.318]} rotation={[1.92, 0, 0]} scale={100} />
                    <group name="Object_343" position={[27.211, 91.533, 59.007]} rotation={[-2.793, 0, -Math.PI]} scale={90.678} />
                    <group name="Object_345" position={[25.825, 92.657, 59.416]} rotation={[-2.793, 0, -Math.PI]} scale={69.292} />
                    <group name="Object_347" position={[35.977, 93.666, 59.783]} rotation={[-2.793, 0, -Math.PI]} scale={60.287} />
                    <group name="Object_349" position={[27.235, 81.095, 55.301]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_351" position={[20.339, 90.278, 58.567]} rotation={[-1.222, 0, 0]} scale={76.614} />
                    <group name="Object_353" position={[20.339, 90.278, 58.567]} rotation={[-1.222, 0, 0]} scale={76.614} />
                    <group name="Object_355" position={[20.339, 92.126, 59.24]} rotation={[-1.222, 0, 0]} scale={76.614} />
                    <group name="Object_357" position={[20.81, 94.278, 60.006]} rotation={[-2.793, 0, -Math.PI]} scale={80} />
                    <group name="Object_359" position={[33.398, 94.813, 60.218]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                    <group name="Object_361" position={[33.398, 94.813, 60.218]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                    <group name="Object_363" position={[30.831, 94.813, 60.218]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                    <group name="Object_365" position={[16.93, 88.898, 58.048]} rotation={[-2.793, 0, -Math.PI]} scale={55.009} />
                    <group name="Object_367" position={[18.887, 89.902, 58.43]} rotation={[-1.222, -Math.PI / 2, 0]} scale={78.592} />
                    <group name="Object_369" position={[18.887, 89.902, 58.43]} rotation={[-1.222, -Math.PI / 2, 0]} scale={78.592} />
                    <group name="Object_371" position={[16.869, 89.902, 58.43]} rotation={[-1.222, -Math.PI / 2, 0]} scale={78.592} />
                    <group name="Object_373" position={[31.51, 96.299, 60.741]} rotation={[-2.793, 0, -Math.PI]} scale={60.287} />
                    <group name="Object_375" position={[37.5, 92.056, 59.214]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                    <group name="Object_377" position={[37.5, 92.056, 59.214]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                    <group name="Object_379" position={[32.952, 92.056, 59.214]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                    <group name="Object_381" position={[34.11, 90.469, 58.619]} rotation={[-2.793, 0, -Math.PI]} scale={80} />
                    <group name="Object_383" position={[19.17, 91.515, 59]} rotation={[-2.793, 0, -Math.PI]} scale={39.451} />
                    <group name="Object_385" position={[39.792, 89.373, 58.22]} rotation={[-2.793, 0, -Math.PI]} scale={39.451} />
                    <group name="Object_387" position={[19.158, 92.066, 59.201]} rotation={[-2.793, 0, -Math.PI]} scale={52.938} />
                    <group name="Object_389" position={[27.235, 81.095, 55.301]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_391" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_393" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_395" position={[-27.818, 0, 14.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_401" position={[27.818, 0, 14.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_407" position={[-55.213, 0, -85.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_413" position={[0, 0, -85.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_419" position={[55.213, 0, -85.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_425" position={[17.04, 27.577, 78.599]} rotation={[-1.74, 0, 0]} scale={100} />
                    <group name="Object_427" position={[32.152, 35.636, 84.974]} rotation={[-1.444, 0, 0]} scale={100} />
                    <group name="Object_429" position={[32.155, 27.526, 75.436]} rotation={[-1.444, 0, 0]} scale={100} />
                    <group name="Object_431" position={[16.904, 27.577, 78.599]} rotation={[-1.583, 0, 0]} scale={100} />
                    <group name="Object_433" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                    <group name="Object_437" position={[66.125, 91.201, 192.315]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_439" position={[66.125, 91.201, 192.315]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_441" position={[14.264, 98.07, 178.427]} rotation={[-1.239, -0.008, -0.215]} scale={42.44} />
                    <group name="Object_444" position={[-30.976, 101.65, 165.682]} rotation={[-1.244, -0.028, -0.215]} scale={42.44} />
                    <group name="Object_447" position={[66.125, 91.201, 192.315]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Object_449" position={[66.125, 90.189, 191.947]} rotation={[-1.222, 0, 0]} scale={174.317} />
                    <skinnedMesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_14.skeleton} />
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_16.skeleton} />
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.chrome} skeleton={nodes.Object_18.skeleton} />
                    <skinnedMesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.blocker} skeleton={nodes.Object_20.skeleton} />
                    <skinnedMesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.pattern_4} skeleton={nodes.Object_22.skeleton} />
                    <skinnedMesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.metal_dark} skeleton={nodes.Object_24.skeleton} />
                    <skinnedMesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_26.skeleton} />
                    <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.light001} skeleton={nodes.Object_27.skeleton} />
                    <skinnedMesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.blocker} skeleton={nodes.Object_28.skeleton} />
                    <skinnedMesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.plastic_matte} skeleton={nodes.Object_30.skeleton} />
                    <skinnedMesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.metal_dark} skeleton={nodes.Object_32.skeleton} />
                    <skinnedMesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_34.skeleton} />
                    <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.blocker} skeleton={nodes.Object_36.skeleton} />
                    <skinnedMesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_38.skeleton} />
                    <skinnedMesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.chrome} skeleton={nodes.Object_40.skeleton} />
                    <skinnedMesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.pattern_4} skeleton={nodes.Object_42.skeleton} />
                    <skinnedMesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.plastic_matte} skeleton={nodes.Object_44.skeleton} />
                    <skinnedMesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.metal_dark} skeleton={nodes.Object_46.skeleton} />
                    <skinnedMesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_48.skeleton} />
                    <skinnedMesh name="Object_49" geometry={nodes.Object_49.geometry} material={materials.light001} skeleton={nodes.Object_49.skeleton} />
                    <skinnedMesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.blocker} skeleton={nodes.Object_50.skeleton} />
                    <skinnedMesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.metal_dark} skeleton={nodes.Object_52.skeleton} />
                    <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.metal_1} skeleton={nodes.Object_54.skeleton} />
                    <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.metal_1} skeleton={nodes.Object_56.skeleton} />
                    <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.metal_1} skeleton={nodes.Object_58.skeleton} />
                    <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.metal_1} skeleton={nodes.Object_60.skeleton} />
                    <skinnedMesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.metal_1} skeleton={nodes.Object_62.skeleton} />
                    <skinnedMesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} skeleton={nodes.Object_64.skeleton} />
                    <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.005']} skeleton={nodes.Object_66.skeleton} />
                    <skinnedMesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.glass} skeleton={nodes.Object_68.skeleton} />
                    <skinnedMesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_70.skeleton} />
                    <skinnedMesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.rubber} skeleton={nodes.Object_72.skeleton} />
                    <skinnedMesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.glass} skeleton={nodes.Object_74.skeleton} />
                    <skinnedMesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.rubber} skeleton={nodes.Object_76.skeleton} />
                    <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_78.skeleton} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_80.skeleton} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.006']} skeleton={nodes.Object_82.skeleton} />
                    <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_84.skeleton} />
                    <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.005']} skeleton={nodes.Object_86.skeleton} />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['Material.006']} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.glass} skeleton={nodes.Object_90.skeleton} />
                    <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.glass} skeleton={nodes.Object_92.skeleton} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.rubber} skeleton={nodes.Object_94.skeleton} />
                    <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_96.skeleton} />
                    <skinnedMesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_98.skeleton} />
                    <skinnedMesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.rubber} skeleton={nodes.Object_100.skeleton} />
                    <skinnedMesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.metal_1} skeleton={nodes.Object_102.skeleton} />
                    <skinnedMesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.metal_1} skeleton={nodes.Object_104.skeleton} />
                    <skinnedMesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.metal_1} skeleton={nodes.Object_106.skeleton} />
                    <skinnedMesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.metal_1} skeleton={nodes.Object_108.skeleton} />
                    <skinnedMesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.metal_1} skeleton={nodes.Object_110.skeleton} />
                    <skinnedMesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.metal_1} skeleton={nodes.Object_112.skeleton} />
                    <skinnedMesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_114.skeleton} />
                    <skinnedMesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_116.skeleton} />
                    <skinnedMesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.chrome} skeleton={nodes.Object_118.skeleton} />
                    <skinnedMesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.blocker} skeleton={nodes.Object_120.skeleton} />
                    <skinnedMesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.pattern_4} skeleton={nodes.Object_122.skeleton} />
                    <skinnedMesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.metal_dark} skeleton={nodes.Object_124.skeleton} />
                    <skinnedMesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_126.skeleton} />
                    <skinnedMesh name="Object_127" geometry={nodes.Object_127.geometry} material={materials.light001} skeleton={nodes.Object_127.skeleton} />
                    <skinnedMesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.blocker} skeleton={nodes.Object_128.skeleton} />
                    <skinnedMesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.plastic_matte} skeleton={nodes.Object_130.skeleton} />
                    <skinnedMesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.metal_dark} skeleton={nodes.Object_132.skeleton} />
                    <skinnedMesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_134.skeleton} />
                    <skinnedMesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_136.skeleton} />
                    <skinnedMesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.blocker} skeleton={nodes.Object_138.skeleton} />
                    <skinnedMesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.chrome} skeleton={nodes.Object_140.skeleton} />
                    <skinnedMesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.pattern_4} skeleton={nodes.Object_142.skeleton} />
                    <skinnedMesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.plastic_matte} skeleton={nodes.Object_144.skeleton} />
                    <skinnedMesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.metal_dark} skeleton={nodes.Object_146.skeleton} />
                    <skinnedMesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_148.skeleton} />
                    <skinnedMesh name="Object_149" geometry={nodes.Object_149.geometry} material={materials.light001} skeleton={nodes.Object_149.skeleton} />
                    <skinnedMesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.blocker} skeleton={nodes.Object_150.skeleton} />
                    <skinnedMesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.metal_dark} skeleton={nodes.Object_152.skeleton} />
                    <skinnedMesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.metal_1} skeleton={nodes.Object_154.skeleton} />
                    <skinnedMesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.metal_1} skeleton={nodes.Object_156.skeleton} />
                    <skinnedMesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.material_0} skeleton={nodes.Object_158.skeleton} />
                    <skinnedMesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.material_0} skeleton={nodes.Object_160.skeleton} />
                    <skinnedMesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.material_0} skeleton={nodes.Object_162.skeleton} />
                    <skinnedMesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material_0} skeleton={nodes.Object_164.skeleton} />
                    <skinnedMesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials['Material.005']} skeleton={nodes.Object_166.skeleton} />
                    <skinnedMesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.glass} skeleton={nodes.Object_168.skeleton} />
                    <skinnedMesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.glass} skeleton={nodes.Object_170.skeleton} />
                    <skinnedMesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_172.skeleton} />
                    <skinnedMesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['Material.006']} skeleton={nodes.Object_174.skeleton} />
                    <skinnedMesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.rubber} skeleton={nodes.Object_176.skeleton} />
                    <skinnedMesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.rubber} skeleton={nodes.Object_178.skeleton} />
                    <skinnedMesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_180.skeleton} />
                    <skinnedMesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_182.skeleton} />
                    <skinnedMesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_184.skeleton} />
                    <skinnedMesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_186.skeleton} />
                    <skinnedMesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Material.005']} skeleton={nodes.Object_188.skeleton} />
                    <skinnedMesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['Material.006']} skeleton={nodes.Object_190.skeleton} />
                    <skinnedMesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.rubber} skeleton={nodes.Object_192.skeleton} />
                    <skinnedMesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_194.skeleton} />
                    <skinnedMesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_196.skeleton} />
                    <skinnedMesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.rubber} skeleton={nodes.Object_198.skeleton} />
                    <skinnedMesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.glass} skeleton={nodes.Object_200.skeleton} />
                    <skinnedMesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.glass} skeleton={nodes.Object_202.skeleton} />
                    <skinnedMesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.metal_1} skeleton={nodes.Object_204.skeleton} />
                    <skinnedMesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.material_0} skeleton={nodes.Object_206.skeleton} />
                    <skinnedMesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.material_0} skeleton={nodes.Object_208.skeleton} />
                    <skinnedMesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.metal_1} skeleton={nodes.Object_210.skeleton} />
                    <skinnedMesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.material_0} skeleton={nodes.Object_212.skeleton} />
                    <skinnedMesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Material.005']} skeleton={nodes.Object_214.skeleton} />
                    <skinnedMesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.glass} skeleton={nodes.Object_216.skeleton} />
                    <skinnedMesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Material.007']} skeleton={nodes.Object_218.skeleton} />
                    <skinnedMesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_220.skeleton} />
                    <skinnedMesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.006']} skeleton={nodes.Object_222.skeleton} />
                    <skinnedMesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Material.008']} skeleton={nodes.Object_224.skeleton} />
                    <skinnedMesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_226.skeleton} />
                    <skinnedMesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.plastic_shiny} skeleton={nodes.Object_228.skeleton} />
                    <skinnedMesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Material.005']} skeleton={nodes.Object_230.skeleton} />
                    <skinnedMesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.taillight_cover} skeleton={nodes.Object_232.skeleton} />
                    <skinnedMesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_234.skeleton} />
                    <skinnedMesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_236.skeleton} />
                    <skinnedMesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_238.skeleton} />
                    <skinnedMesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_240.skeleton} />
                    <skinnedMesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_242.skeleton} />
                    <skinnedMesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.floormat} skeleton={nodes.Object_244.skeleton} />
                    <skinnedMesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.floormat} skeleton={nodes.Object_246.skeleton} />
                    <skinnedMesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.floormat} skeleton={nodes.Object_248.skeleton} />
                    <skinnedMesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_250.skeleton} />
                    <skinnedMesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_252.skeleton} />
                    <skinnedMesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.glass} skeleton={nodes.Object_254.skeleton} />
                    <skinnedMesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_256.skeleton} />
                    <skinnedMesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.chrome} skeleton={nodes.Object_258.skeleton} />
                    <skinnedMesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_260.skeleton} />
                    <skinnedMesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_262.skeleton} />
                    <skinnedMesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_264.skeleton} />
                    <skinnedMesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_266.skeleton} />
                    <skinnedMesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.taillight_chrome} skeleton={nodes.Object_268.skeleton} />
                    <skinnedMesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.glass} skeleton={nodes.Object_270.skeleton} />
                    <skinnedMesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.plastic_matte} skeleton={nodes.Object_272.skeleton} />
                    <skinnedMesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.plastic_matte} skeleton={nodes.Object_274.skeleton} />
                    <skinnedMesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_276.skeleton} />
                    <skinnedMesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Material.005']} skeleton={nodes.Object_278.skeleton} />
                    <skinnedMesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_280.skeleton} />
                    <skinnedMesh name="Object_281" geometry={nodes.Object_281.geometry} material={materials.blockerBlackHole} skeleton={nodes.Object_281.skeleton} />
                    <skinnedMesh name="Object_283" geometry={nodes.Object_283.geometry} material={materials.blockerBlackHole} skeleton={nodes.Object_283.skeleton} />
                    <skinnedMesh name="Object_285" geometry={nodes.Object_285.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_285.skeleton} />
                    <skinnedMesh name="Object_287" geometry={nodes.Object_287.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_287.skeleton} />
                    <skinnedMesh name="Object_289" geometry={nodes.Object_289.geometry} material={materials.plastic_smooth} skeleton={nodes.Object_289.skeleton} />
                    <skinnedMesh name="Object_291" geometry={nodes.Object_291.geometry} material={materials.light001} skeleton={nodes.Object_291.skeleton} />
                    <skinnedMesh name="Object_293" geometry={nodes.Object_293.geometry} material={materials.metal_dark} skeleton={nodes.Object_293.skeleton} />
                    <skinnedMesh name="Object_295" geometry={nodes.Object_295.geometry} material={materials.metal_dark} skeleton={nodes.Object_295.skeleton} />
                    <skinnedMesh name="Object_297" geometry={nodes.Object_297.geometry} material={materials.metal_dark} skeleton={nodes.Object_297.skeleton} />
                    <skinnedMesh name="Object_299" geometry={nodes.Object_299.geometry} material={materials.ground_shadow} skeleton={nodes.Object_299.skeleton} />
                    <skinnedMesh name="Object_301" geometry={nodes.Object_301.geometry} material={materials['Material.002']} skeleton={nodes.Object_301.skeleton} />
                    <skinnedMesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Material.003']} skeleton={nodes.Object_302.skeleton} />
                    <skinnedMesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Material.002']} skeleton={nodes.Object_304.skeleton} />
                    <skinnedMesh name="Object_305" geometry={nodes.Object_305.geometry} material={materials['Material.003']} skeleton={nodes.Object_305.skeleton} />
                    <skinnedMesh name="Object_307" geometry={nodes.Object_307.geometry} material={materials['Material.002']} skeleton={nodes.Object_307.skeleton} />
                    <skinnedMesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.003']} skeleton={nodes.Object_308.skeleton} />
                    <skinnedMesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Material.002']} skeleton={nodes.Object_310.skeleton} />
                    <skinnedMesh name="Object_311" geometry={nodes.Object_311.geometry} material={materials['Material.003']} skeleton={nodes.Object_311.skeleton} />
                    <skinnedMesh name="Object_313" geometry={nodes.Object_313.geometry} material={materials['Material.011']} skeleton={nodes.Object_313.skeleton} />
                    <skinnedMesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Material.028']} skeleton={nodes.Object_314.skeleton} />
                    <skinnedMesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Material.011']} skeleton={nodes.Object_316.skeleton} />
                    <skinnedMesh name="Object_317" geometry={nodes.Object_317.geometry} material={materials['Material.028']} skeleton={nodes.Object_317.skeleton} />
                    <skinnedMesh name="Object_319" geometry={nodes.Object_319.geometry} material={materials['Material.011']} skeleton={nodes.Object_319.skeleton} />
                    <skinnedMesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials['Material.028']} skeleton={nodes.Object_320.skeleton} />
                    <skinnedMesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials['Material.011']} skeleton={nodes.Object_322.skeleton} />
                    <skinnedMesh name="Object_323" geometry={nodes.Object_323.geometry} material={materials['Material.028']} skeleton={nodes.Object_323.skeleton} />
                    <skinnedMesh name="Object_325" geometry={nodes.Object_325.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_325.skeleton} />
                    <skinnedMesh name="Object_327" geometry={nodes.Object_327.geometry} material={materials.pattern_4} skeleton={nodes.Object_327.skeleton} />
                    <skinnedMesh name="Object_329" geometry={nodes.Object_329.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_329.skeleton} />
                    <skinnedMesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.chrome} skeleton={nodes.Object_331.skeleton} />
                    <skinnedMesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_333.skeleton} />
                    <skinnedMesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.light001} skeleton={nodes.Object_335.skeleton} />
                    <skinnedMesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_337.skeleton} />
                    <skinnedMesh name="Object_338" geometry={nodes.Object_338.geometry} material={materials.blocker} skeleton={nodes.Object_338.skeleton} />
                    <skinnedMesh name="Object_340" geometry={nodes.Object_340.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_340.skeleton} />
                    <skinnedMesh name="Object_342" geometry={nodes.Object_342.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_342.skeleton} />
                    <skinnedMesh name="Object_344" geometry={nodes.Object_344.geometry} material={materials.light001} skeleton={nodes.Object_344.skeleton} />
                    <skinnedMesh name="Object_346" geometry={nodes.Object_346.geometry} material={materials.light001} skeleton={nodes.Object_346.skeleton} />
                    <skinnedMesh name="Object_348" geometry={nodes.Object_348.geometry} material={materials.light001} skeleton={nodes.Object_348.skeleton} />
                    <skinnedMesh name="Object_350" geometry={nodes.Object_350.geometry} material={materials.light001} skeleton={nodes.Object_350.skeleton} />
                    <skinnedMesh name="Object_352" geometry={nodes.Object_352.geometry} material={materials.light001} skeleton={nodes.Object_352.skeleton} />
                    <skinnedMesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials.light001} skeleton={nodes.Object_354.skeleton} />
                    <skinnedMesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.light001} skeleton={nodes.Object_356.skeleton} />
                    <skinnedMesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials.light001} skeleton={nodes.Object_358.skeleton} />
                    <skinnedMesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials.light001} skeleton={nodes.Object_360.skeleton} />
                    <skinnedMesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials.light001} skeleton={nodes.Object_362.skeleton} />
                    <skinnedMesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials.light001} skeleton={nodes.Object_364.skeleton} />
                    <skinnedMesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials.light001} skeleton={nodes.Object_366.skeleton} />
                    <skinnedMesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials.light001} skeleton={nodes.Object_368.skeleton} />
                    <skinnedMesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials.light001} skeleton={nodes.Object_370.skeleton} />
                    <skinnedMesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials.light001} skeleton={nodes.Object_372.skeleton} />
                    <skinnedMesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials.light001} skeleton={nodes.Object_374.skeleton} />
                    <skinnedMesh name="Object_376" geometry={nodes.Object_376.geometry} material={materials.light001} skeleton={nodes.Object_376.skeleton} />
                    <skinnedMesh name="Object_378" geometry={nodes.Object_378.geometry} material={materials.light001} skeleton={nodes.Object_378.skeleton} />
                    <skinnedMesh name="Object_380" geometry={nodes.Object_380.geometry} material={materials.light001} skeleton={nodes.Object_380.skeleton} />
                    <skinnedMesh name="Object_382" geometry={nodes.Object_382.geometry} material={materials.light001} skeleton={nodes.Object_382.skeleton} />
                    <skinnedMesh name="Object_384" geometry={nodes.Object_384.geometry} material={materials.light001} skeleton={nodes.Object_384.skeleton} />
                    <skinnedMesh name="Object_386" geometry={nodes.Object_386.geometry} material={materials.light001} skeleton={nodes.Object_386.skeleton} />
                    <skinnedMesh name="Object_388" geometry={nodes.Object_388.geometry} material={materials.light001} skeleton={nodes.Object_388.skeleton} />
                    <skinnedMesh name="Object_390" geometry={nodes.Object_390.geometry} material={materials.blockerBlackHole} skeleton={nodes.Object_390.skeleton} />
                    <skinnedMesh name="Object_392" geometry={nodes.Object_392.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_392.skeleton} />
                    <skinnedMesh name="Object_394" geometry={nodes.Object_394.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_394.skeleton} />
                    <skinnedMesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials.pattern_4} skeleton={nodes.Object_396.skeleton} />
                    <skinnedMesh name="Object_397" geometry={nodes.Object_397.geometry} material={materials.blocker} skeleton={nodes.Object_397.skeleton} />
                    <skinnedMesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_398.skeleton} />
                    <skinnedMesh name="Object_399" geometry={nodes.Object_399.geometry} material={materials.plastic_matte} skeleton={nodes.Object_399.skeleton} />
                    <skinnedMesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials.metal_dark} skeleton={nodes.Object_400.skeleton} />
                    <skinnedMesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials.pattern_4} skeleton={nodes.Object_402.skeleton} />
                    <skinnedMesh name="Object_403" geometry={nodes.Object_403.geometry} material={materials.blocker} skeleton={nodes.Object_403.skeleton} />
                    <skinnedMesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_404.skeleton} />
                    <skinnedMesh name="Object_405" geometry={nodes.Object_405.geometry} material={materials.plastic_matte} skeleton={nodes.Object_405.skeleton} />
                    <skinnedMesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials.metal_dark} skeleton={nodes.Object_406.skeleton} />
                    <skinnedMesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials.pattern_4} skeleton={nodes.Object_408.skeleton} />
                    <skinnedMesh name="Object_409" geometry={nodes.Object_409.geometry} material={materials.blocker} skeleton={nodes.Object_409.skeleton} />
                    <skinnedMesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_410.skeleton} />
                    <skinnedMesh name="Object_411" geometry={nodes.Object_411.geometry} material={materials.plastic_matte} skeleton={nodes.Object_411.skeleton} />
                    <skinnedMesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.metal_dark} skeleton={nodes.Object_412.skeleton} />
                    <skinnedMesh name="Object_414" geometry={nodes.Object_414.geometry} material={materials.pattern_4} skeleton={nodes.Object_414.skeleton} />
                    <skinnedMesh name="Object_415" geometry={nodes.Object_415.geometry} material={materials.blocker} skeleton={nodes.Object_415.skeleton} />
                    <skinnedMesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_416.skeleton} />
                    <skinnedMesh name="Object_417" geometry={nodes.Object_417.geometry} material={materials.plastic_matte} skeleton={nodes.Object_417.skeleton} />
                    <skinnedMesh name="Object_418" geometry={nodes.Object_418.geometry} material={materials.metal_dark} skeleton={nodes.Object_418.skeleton} />
                    <skinnedMesh name="Object_420" geometry={nodes.Object_420.geometry} material={materials.pattern_4} skeleton={nodes.Object_420.skeleton} />
                    <skinnedMesh name="Object_421" geometry={nodes.Object_421.geometry} material={materials.blocker} skeleton={nodes.Object_421.skeleton} />
                    <skinnedMesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials['plastic_smooth.001']} skeleton={nodes.Object_422.skeleton} />
                    <skinnedMesh name="Object_423" geometry={nodes.Object_423.geometry} material={materials.plastic_matte} skeleton={nodes.Object_423.skeleton} />
                    <skinnedMesh name="Object_424" geometry={nodes.Object_424.geometry} material={materials.metal_dark} skeleton={nodes.Object_424.skeleton} />
                    <skinnedMesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials.Metal_3} skeleton={nodes.Object_426.skeleton} />
                    <skinnedMesh name="Object_428" geometry={nodes.Object_428.geometry} material={materials.Metal_3} skeleton={nodes.Object_428.skeleton} />
                    <skinnedMesh name="Object_430" geometry={nodes.Object_430.geometry} material={materials['metal_dark.001']} skeleton={nodes.Object_430.skeleton} />
                    <skinnedMesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials['metal_dark.001']} skeleton={nodes.Object_432.skeleton} />
                    <skinnedMesh name="Object_434" geometry={nodes.Object_434.geometry} material={materials.plastic_matte} skeleton={nodes.Object_434.skeleton} />
                    <skinnedMesh name="Object_435" geometry={nodes.Object_435.geometry} material={materials['Material.005']} skeleton={nodes.Object_435.skeleton} />
                    {/* <skinnedMesh name="Object_436" geometry={nodes.Object_436.geometry} material={materials.chrome} skeleton={nodes.Object_436.skeleton} /> */}
                     {/* <skinnedMesh name="Object_438" geometry={nodes.Object_438.geometry} material={materials['Material.031']} skeleton={nodes.Object_438.skeleton} /> */}
                    {/* <skinnedMesh name="Object_442" geometry={nodes.Object_442.geometry} material={materials['Material.031']} skeleton={nodes.Object_442.skeleton} /> */}
                    {/* <skinnedMesh name="Object_443" geometry={nodes.Object_443.geometry} material={materials['Material.032']} skeleton={nodes.Object_443.skeleton} /> */}
                    {/* <skinnedMesh name="Object_445" geometry={nodes.Object_445.geometry} material={materials['Material.031']} skeleton={nodes.Object_445.skeleton} /> */}
                    {/* <skinnedMesh name="Object_446" geometry={nodes.Object_446.geometry} material={materials['Material.032']} skeleton={nodes.Object_446.skeleton} /> */}
                    {/* <skinnedMesh name="Object_448" geometry={nodes.Object_448.geometry} material={materials['Material.031']} skeleton={nodes.Object_448.skeleton} />  */}
                    <skinnedMesh name="Object_450" geometry={nodes.Object_450.geometry} material={materials['Material.031']} skeleton={nodes.Object_450.skeleton} />
                  </group>
                </group>
                <group name="Cube018" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube020" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube021" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube022" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube023" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="nut012" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube028" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube029" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube033" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube169" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube170" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube171" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube172" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube173" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube174" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube175" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Cube176" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="nut013" rotation={[-1.501, 0, 0]} scale={100} />
                <group name="Empty064" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Empty065" position={[0, 0, -0.451]} />
                </group>
                <group name="Plane050" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane051" position={[103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder003" position={[103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube120" position={[103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, Math.PI / 3]} scale={100} />
                <group name="Cube128" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, Math.PI / 3]} scale={100} />
                <group name="Cylinder004" position={[103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube010" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube013" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube127" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube007" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube103" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube133" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube140" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube141" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube017" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube185" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube186" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube187" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube188" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube189" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube190" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube191" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube192" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube193" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane062" position={[-103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder017" position={[-103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube194" position={[-103.714, 33.877, 77.768]} rotation={[-Math.PI / 2, 0, -Math.PI / 3]} scale={100} />
                <group name="Plane128" position={[-103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder018" position={[-103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube195" position={[-103.714, 78.975, 77.768]} rotation={[-Math.PI / 2, 0, -Math.PI / 3]} scale={100} />
                <group name="Cube102" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube104" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube105" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube106" rotation={[-1.518, 0, 0]} scale={100} />
                <group name="Cube107" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="nut023" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube108" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube109" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube110" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube177" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube178" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube179" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube180" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube181" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube182" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube183" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube184" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="nut014" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Empty066" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="Empty067" position={[0, 0, -0.504]} />
                </group>
                <group name="Plane056" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
                <group name="Plane057" position={[104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100} />
                <group name="Cube130" position={[104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder011" position={[104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube131" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder012" position={[104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube009" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube012" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube137" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube129" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube016" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube136" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube138" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube143" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube135" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube142" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube196" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube197" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube198" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube199" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube200" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube201" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube202" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube203" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube204" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane129" position={[-104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
                <group name="Cylinder019" position={[-104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube205" position={[-104.583, 35.251, -29.777]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="Plane009" position={[-104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100} />
                <group name="Cylinder022" position={[-104.583, 85.69, -29.777]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube001" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube002" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube003" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube004" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube005" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube006" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube008" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube011" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube014" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube015" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube132" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube134" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube139" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube144" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube019" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube145" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube146" position={[0, 0, 84.93]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube149" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube150" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube151" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube152" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube153" position={[0, 133.281, 34.566]} rotation={[-Math.PI / 2, 0, -0.179]} scale={100}>
                  <group name="Cube154" position={[0.075, 133.281, 34.15]} rotation={[-Math.PI / 2, 0, -0.179]} scale={100} />
                </group>
                <group name="Cube155" position={[0, 133.281, 34.566]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube156" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube157" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube158" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube159" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube160" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube161" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube162" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube163" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube164" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube165" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube166" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube167" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube168" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Text039" position={[4.576, 90.443, 137.249]} rotation={[-2.836, 0, Math.PI]} scale={50.452} />
                <group name="nut034" position={[15.966, 136.798, 35.148]} rotation={[-Math.PI, 0, 0]} scale={100}>
                  <mesh name="nut034_metal_dark_0" geometry={nodes.nut034_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="nut035" position={[18.946, 136.798, 35.148]} rotation={[-Math.PI, 0, 0]} scale={100}>
                  <mesh name="nut035_metal_dark_0" geometry={nodes.nut035_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="nut036" position={[17.469, 136.798, 32.624]} rotation={[-Math.PI, 0, 0]} scale={100}>
                  <mesh name="nut036_metal_dark_0" geometry={nodes.nut036_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="nut039" position={[0.04, 136.798, 32.624]} rotation={[-Math.PI, 0, 0]} scale={100} />
                <group name="nut015" position={[-18.935, 136.798, 35.148]} rotation={[-Math.PI, 0, 0]} scale={100}>
                  <mesh name="nut015_metal_dark_0" geometry={nodes.nut015_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="nut024" position={[-15.954, 136.798, 35.148]} rotation={[-Math.PI, 0, 0]} scale={100}>
                  <mesh name="nut024_metal_dark_0" geometry={nodes.nut024_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="nut025" position={[-17.431, 136.798, 32.624]} rotation={[-Math.PI, 0, 0]} scale={100}>
                  <mesh name="nut025_metal_dark_0" geometry={nodes.nut025_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Cylinder013" position={[17.429, 137.086, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={[147.416, 147.416, 98.074]}>
                  <mesh name="Cylinder013_metal_dark_0" geometry={nodes.Cylinder013_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Cylinder014" position={[-0.001, 137.086, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={[147.416, 147.416, 98.074]} />
                <group name="Cylinder020" position={[-17.429, 137.086, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={[147.416, 147.416, 98.074]}>
                  <mesh name="Cylinder020_metal_dark_0" geometry={nodes.Cylinder020_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="BezierCurve002" position={[17.429, 136.82, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="BezierCurve002_metal_dark_0" geometry={nodes.BezierCurve002_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Cylinder015" position={[17.429, 136.82, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder015_metal_dark_0" geometry={nodes.Cylinder015_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Cylinder016" position={[0, 136.82, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="BezierCurve003" position={[-17.474, 136.82, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="BezierCurve003_metal_dark_0" geometry={nodes.BezierCurve003_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="Cylinder021" position={[-17.474, 136.82, 34.286]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Cylinder021_metal_dark_0" geometry={nodes.Cylinder021_metal_dark_0.geometry} material={materials.metal_dark} />
                </group>
                <group name="ground_shadow" position={[0, 3.363, -11.952]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane" position={[90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="Plane001" position={[90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="Plane002" position={[-90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="Plane004" position={[-90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={100} />
                <group name="Cube049" position={[90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube032" position={[90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube206" position={[-90.637, 47.135, 130.298]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cube207" position={[-90.637, 47.135, -177.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="INTERIOR_system_pos" position={[27.818, 0, 14.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <group name="seats_Empty" />
                  <group name="Empty_deat_T2" position={[-0.006, 0.197, 0.293]}>
                    <group name="Empty_seat_T2_lower_part" rotation={[-Math.PI / 9, 0, 0]} />
                    <group name="Empty_seat_T2_upper_part" />
                  </group>
                  <group name="SW_Empty" position={[-0.006, -0.218, 0.806]} rotation={[Math.PI / 9, 0, 0]}>
                    <group name="Cube043" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Cube044" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Cube045" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Cube046" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Torus" position={[27.235, 80.594, 36.272]} rotation={[-2.793, 0, 0]} scale={100} />
                    <group name="Torus009" position={[27.235, 80.594, 36.272]} rotation={[-2.793, 0, 0]} scale={100} />
                    <group name="SW_base" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Cube034" position={[34.456, 69.39, 63.318]} rotation={[-1.222, 0, 0]} scale={100} />
                    <group name="Cube035" position={[20.209, 69.39, 63.318]} rotation={[1.92, 0, 0]} scale={100} />
                  </group>
                  <group name="Dash_Empty" position={[-0.006, -0.451, 0.931]}>
                    <group name="Empty058" position={[0, -0.367, -0.261]} rotation={[Math.PI / 9, 0, 0]}>
                      <group name="Empty062" position={[0, 0.435, 0.12]}>
                        <group name="Text023" position={[27.211, 91.533, 59.007]} rotation={[-2.793, 0, Math.PI]} scale={90.678} />
                        <group name="Text024" position={[25.825, 92.657, 59.416]} rotation={[-2.793, 0, Math.PI]} scale={69.292} />
                        <group name="Text025" position={[35.977, 93.666, 59.783]} rotation={[-2.793, 0, Math.PI]} scale={60.287} />
                        <group name="Cube089" position={[27.235, 81.095, 55.301]} rotation={[-1.222, 0, 0]} scale={100} />
                        <group name="Cube090" position={[20.339, 92.126, 59.24]} rotation={[-1.222, 0, 0]} scale={76.614}>
                          <group name="Cube091" position={[20.339, 90.278, 58.567]} rotation={[-1.222, 0, 0]} scale={76.614} />
                          <group name="Cube098" position={[20.339, 90.278, 58.567]} rotation={[-1.222, 0, 0]} scale={76.614} />
                        </group>
                        <group name="Text026" position={[20.81, 94.278, 60.006]} rotation={[-2.793, 0, Math.PI]} scale={80} />
                        <group name="Cube092" position={[30.831, 94.813, 60.218]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100}>
                          <group name="Cube093" position={[33.398, 94.813, 60.218]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                          <group name="Cube094" position={[33.398, 94.813, 60.218]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                        </group>
                        <group name="Text027" position={[16.93, 88.898, 58.048]} rotation={[-2.793, 0, Math.PI]} scale={55.009} />
                        <group name="Cube095" position={[16.869, 89.902, 58.43]} rotation={[-1.222, -Math.PI / 2, 0]} scale={78.592}>
                          <group name="Cube096" position={[18.887, 89.902, 58.43]} rotation={[-1.222, -Math.PI / 2, 0]} scale={78.592} />
                          <group name="Cube097" position={[18.887, 89.902, 58.43]} rotation={[-1.222, -Math.PI / 2, 0]} scale={78.592} />
                        </group>
                        <group name="Text028" position={[31.51, 96.299, 60.741]} rotation={[-2.793, 0, Math.PI]} scale={60.287} />
                        <group name="Cube099" position={[32.952, 92.056, 59.214]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100}>
                          <group name="Cube100" position={[37.5, 92.056, 59.214]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                          <group name="Cube101" position={[37.5, 92.056, 59.214]} rotation={[-1.222, -Math.PI / 2, 0]} scale={100} />
                        </group>
                        <group name="Text029" position={[34.11, 90.469, 58.619]} rotation={[-2.793, 0, Math.PI]} scale={80} />
                        <group name="Text030" position={[19.17, 91.515, 59]} rotation={[-2.793, 0, Math.PI]} scale={39.451} />
                        <group name="Text031" position={[39.792, 89.373, 58.22]} rotation={[-2.793, 0, Math.PI]} scale={39.451} />
                        <group name="Text032" position={[19.158, 92.066, 59.201]} rotation={[-2.793, 0, Math.PI]} scale={52.938} />
                      </group>
                      <group name="Cube059" position={[27.235, 81.095, 55.301]} rotation={[-1.222, 0, 0]} scale={100} />
                      <group name="SW_base005" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                      <group name="SW_base006" position={[27.235, 80.594, 36.272]} rotation={[-1.222, 0, 0]} scale={100} />
                    </group>
                  </group>
                </group>
                <group name="seat" position={[-27.818, 0, 14.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="seat004" position={[27.818, 0, 14.518]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="seat003" position={[-55.213, 0, -85.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="seat001" position={[0, 0, -85.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="seat002" position={[55.213, 0, -85.897]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Plane166" position={[17.04, 27.577, 78.599]} rotation={[-1.74, 0, 0]} scale={100} />
                <group name="Plane167" position={[32.152, 35.636, 84.974]} rotation={[-1.444, 0, 0]} scale={100} />
                <group name="Plane168" position={[32.155, 27.526, 75.436]} rotation={[-1.444, 0, 0]} scale={100} />
                <group name="Plane169" position={[16.904, 27.577, 78.599]} rotation={[-1.583, 0, 0]} scale={100} />
                <group name="side_mirror_534" rotation={[-Math.PI / 2, 0, 0]} scale={100} />
                <group name="Cylinder115" position={[66.125, 90.189, 191.947]} rotation={[-1.222, 0, 0]} scale={174.317}>
                  <group name="Plane245" position={[66.125, 91.201, 192.315]} rotation={[-1.222, 0, 0]} scale={100} />
                  <group name="Plane197" position={[66.125, 91.201, 192.315]} rotation={[-1.222, 0, 0]} scale={100} />
                  <group name="Cube147" position={[14.264, 98.07, 178.427]} rotation={[-1.239, -0.008, -0.215]} scale={42.44} />
                  <group name="Cube148" position={[-30.976, 101.65, 165.682]} rotation={[-1.244, -0.028, -0.215]} scale={42.44} />
                  <group name="Plane246" position={[66.125, 91.201, 192.315]} rotation={[-1.222, 0, 0]} scale={100} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/freeconcept3.gltf')
