/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 hongqi.gltf 
Author: Davidson (https://sketchfab.com/a0930582398)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hongqi-h9-bbcbdc697a614c25a5b02ce2a4b2c6ca
Title: hongqi h9
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hongqi.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={1}  rotation={[0.4,-2.8,0]} position={[2,0,0]}>
        <group position={[2.136, 1.7, -3.291]}>
          <mesh geometry={nodes.mesh_0_0nr_mat_0_0.geometry} material={materials.mat_0} />
          <mesh geometry={nodes.mesh_0_1nr_mat_0_0.geometry} material={materials.mat_0} />
          <mesh geometry={nodes.mesh_0_2nr_mat_0_0.geometry} material={materials.mat_0} />
          <mesh geometry={nodes.mesh_0_3nr_mat_0_0.geometry} material={materials.mat_0} />
          <mesh geometry={nodes.mesh_0_4nr_mat_1_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes.mesh_0_5nr_mat_1_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes.mesh_0_6nr_mat_1_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes.mesh_0_7nr_mat_1_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes.mesh_0_8nr_mat_2_0.geometry} material={materials['mat_0.002_0']} />
          <mesh geometry={nodes.mesh_0_9nr_mat_2_0.geometry} material={materials['mat_0.002_0']} />
          <mesh geometry={nodes.mesh_0_10nr_mat_2_0.geometry} material={materials['mat_0.002_0']} />
          <mesh geometry={nodes.mesh_0_11nr_mat_2_0.geometry} material={materials['mat_0.002_0']} />
          <mesh geometry={nodes.mesh_0_12nr_mat_3_0.geometry} material={materials['mat_0.002_1']} />
          <mesh geometry={nodes.mesh_0_13nr_mat_3_0.geometry} material={materials['mat_0.002_1']} />
          <mesh geometry={nodes.mesh_0_14nr_mat_3_0.geometry} material={materials['mat_0.002_1']} />
          <mesh geometry={nodes.mesh_0_15nr_mat_3_0.geometry} material={materials['mat_0.002_1']} />
          <mesh geometry={nodes['mesh_0_16nr_mat_0001_#3_0'].geometry} material={materials['mat_0.001_3']} />
          <mesh geometry={nodes['mesh_0_17nr_mat_0001_#3_0'].geometry} material={materials['mat_0.001_3']} />
          <mesh geometry={nodes['mesh_0_18nr_mat_0001_#3_0'].geometry} material={materials['mat_0.001_3']} />
          <mesh geometry={nodes['mesh_0_19nr_mat_0001_#3_0'].geometry} material={materials['mat_0.001_3']} />
          <mesh geometry={nodes.mesh_0_20nr_mat_4_0.geometry} material={materials['mat_0.002_2']} />
          <mesh geometry={nodes.mesh_0_21nr_mat_4_0.geometry} material={materials['mat_0.002_2']} />
          <mesh geometry={nodes.mesh_0_22nr_mat_4_0.geometry} material={materials['mat_0.002_2']} />
          <mesh geometry={nodes.mesh_0_23nr_mat_4_0.geometry} material={materials['mat_0.002_2']} />
          <mesh geometry={nodes.mesh_0_24nr_mat_5_0.geometry} material={materials.mat_5} />
          <mesh geometry={nodes['mesh_0_25nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_26nr_mat_1_#1_0'].geometry} material={materials.mat_1_1} />
          <mesh geometry={nodes.mesh_0_27nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_28nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_29nr_mat_7_0.geometry} material={materials.mat_7} />
          <mesh geometry={nodes.mesh_0_30nr_mat_1_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes['mesh_0_32nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_33nr_mat_8_0.geometry} material={materials['mat_0.002_3']} />
          <mesh geometry={nodes['mesh_0_34nr_mat_1_#3_0'].geometry} material={materials.mat_1_1_0} />
          <mesh geometry={nodes.mesh_0_35nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_36nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_37nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_39nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_40nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_41nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes['mesh_0_42nr_mat_1_#3_0'].geometry} material={materials.mat_1_1_0} />
          <mesh geometry={nodes.mesh_0_43nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_44nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes['mesh_0_45nr_mat_1_#2_0'].geometry} material={materials.mat_1_2} />
          <mesh geometry={nodes.mesh_0_46nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes['mesh_0_47nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_48nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_49nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes.mesh_0_50nr_mat_8_0.geometry} material={materials['mat_0.002_3']} />
          <mesh geometry={nodes['mesh_0_51nr_mat_1_#3_0'].geometry} material={materials.mat_1_1_0} />
          <mesh geometry={nodes.mesh_0_52nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_53nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_54nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_55nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_56nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_57nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes['mesh_0_58nr_mat_1_#3_0'].geometry} material={materials.mat_1_1_0} />
          <mesh geometry={nodes.mesh_0_60nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_61nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes['mesh_0_62nr_mat_1_#2_0'].geometry} material={materials.mat_1_2} />
          <mesh geometry={nodes.mesh_0_63nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes['mesh_0_64nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_65nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_66nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_67nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes.mesh_0_68nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_69nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_70nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_71nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_72nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_73nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_74nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_0_75nr_mat_1_#3_0'].geometry} material={materials.mat_1_1_0} />
          <mesh geometry={nodes.mesh_0_76nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes.mesh_0_77nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes['mesh_0_78nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_79nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_80nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes.mesh_0_81nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_82nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_83nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_84nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_85nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes.mesh_0_86nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes['mesh_0_87nr_mat_1_#3_0'].geometry} material={materials.mat_1_1_0} />
          <mesh geometry={nodes.mesh_0_88nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_89nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes.mesh_0_90nr_mat_9_0.geometry} material={materials['mat_0.002_4']} />
          <mesh geometry={nodes['mesh_0_91nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_92nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_93nr_mat_1_#1_0'].geometry} material={materials.mat_1_1} />
          <mesh geometry={nodes.mesh_0_94nr_mat_6_0.geometry} material={materials['mat_0.002_5']} />
          <mesh geometry={nodes.mesh_0_95nr_mat_8_0.geometry} material={materials['mat_0.002_3']} />
          <mesh geometry={nodes['mesh_0_96nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_97nr_mat_5_0.geometry} material={materials.mat_5} />
          <mesh geometry={nodes['mesh_0_98nr_mat_1_#1_0'].geometry} material={materials.mat_1_1} />
          <mesh geometry={nodes.mesh_0_99nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_100nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_101nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_0_102nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_103nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_0_104nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_105nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_106nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_107nr_mat_1001_0.geometry} material={materials['mat_0.002_5']} />
          <mesh geometry={nodes['mesh_0_108nr_mat_0001_#1_0'].geometry} material={materials['mat_0.001_1']} />
          <mesh geometry={nodes.mesh_0_109nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_0_110nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_111nr_mat_5_0.geometry} material={materials.mat_5} />
          <mesh geometry={nodes.mesh_0_112nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_0_113nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes.mesh_0_114nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_115nr_mat_4001_0.geometry} material={materials['mat_4.001']} />
          <mesh geometry={nodes.mesh_0_116nr_mat_1001_0.geometry} material={materials['mat_0.002_5']} />
          <mesh geometry={nodes['mesh_0_117nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_0_118nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes['mesh_0_119nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_0_120nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_0_121nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_0_122nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_0_123nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_124nr_mat_1001_0.geometry} material={materials['mat_0.002_5']} />
          <mesh geometry={nodes.mesh_0_125nr_mat_2001_0.geometry} material={materials['mat_2.001']} />
          <mesh geometry={nodes['mesh_0_126nr_mat_0001_#1_0'].geometry} material={materials['mat_0.001_1']} />
          <mesh geometry={nodes.mesh_0_127nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_128nr_mat_4001_0.geometry} material={materials['mat_4.001']} />
          <mesh geometry={nodes.mesh_0_129nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_0_130nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_131nr_mat_0002_0.geometry} material={materials['mat_0.002_6']} />
          <mesh geometry={nodes.mesh_0_132nr_mat_1002_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes['mesh_0_133nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_0_134nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_0_135nr_mat_1002_0.geometry} material={materials['mat_0.002']} />
          <mesh geometry={nodes.mesh_0_136nr_mat_3002_0.geometry} material={materials['mat_0.002_7']} />
          <mesh geometry={nodes.mesh_0_137nr_mat_2002_0.geometry} material={materials['mat_0.002_5']} />
          <mesh geometry={nodes.mesh_0_138nr_mat_4002_0.geometry} material={materials['mat_0.002_8']} />
          <mesh geometry={nodes.mesh_0_140nr_mat_6001_0.geometry} material={materials['mat_0.002_9']} />
          <mesh geometry={nodes['mesh_0_142nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes.mesh_0_143nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_144nr_mat_6001_0.geometry} material={materials['mat_0.002_9']} />
          <mesh geometry={nodes['mesh_0_147nr_mat_1002_#1_0'].geometry} material={materials['mat_1.002_1']} />
          <mesh geometry={nodes['mesh_0_148nr_mat_1002_#1_0'].geometry} material={materials['mat_1.002_1']} />
          <mesh geometry={nodes['mesh_0_149nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_150nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_151nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_152nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_153nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_154nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_156nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_157nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes['mesh_0_158nr_mat_0003_#1_0'].geometry} material={materials['mat_0.003_1']} />
          <mesh geometry={nodes.mesh_1_160nr_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes['mesh_1_161nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_1_162nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes['mesh_1_164nr_mat_0001_#2_0'].geometry} material={materials['mat_0.001_2']} />
          <mesh geometry={nodes.mesh_1_165nr_mat_7_0.geometry} material={materials.mat_7} />
          <mesh geometry={nodes.mesh_1_166nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes.mesh_1_168nr_mat_2003_0.geometry} material={materials['mat_2.003']} />
          <mesh geometry={nodes['mesh_1_169nr_mat_6_#1_0'].geometry} material={materials.mat_6_1} />
          <mesh geometry={nodes.mesh_1_170nr_mat_3001_0.geometry} material={materials['mat_3.001']} />
          <mesh geometry={nodes.mesh_0_36nr001_mat_0001_0.geometry} material={materials['mat_0.001']} />
          <mesh geometry={nodes.mesh_0_53nr001_mat_9002_0.geometry} material={materials['mat_0.002_4']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/hongqi.gltf')
