/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 sportscar.gltf 
Author: AbdulRahim (https://sketchfab.com/IshmalAdil)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sports-lite-e41dae7d6a0945788fa1a47b9bb3563c
Title: Sports Lite
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/sportscar.gltf')
  return (
    <group {...props} dispose={null} scale={0.012} position={[1,0,0]} rotation={[0.3,0.8,0]}>
      <group position={[110,-25,142]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Wheel_RL_Rims_Disc_0.geometry} material={materials.Rims_Disc} />
        <mesh geometry={nodes.Wheel_RL_Rims_0.geometry} material={materials.Rims} />
        <mesh geometry={nodes.Wheel_RL_Tire_Treads_0.geometry} material={materials.Tire_Treads} />
        <mesh geometry={nodes.Wheel_RL_Tire_Sidewall_0.geometry} material={materials.Tire_Sidewall} />
      </group>
      <group position={[-110,-25,142]}  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Wheel_RR_Rims_Disc_0.geometry} material={materials.Rims_Disc} />
        <mesh geometry={nodes.Wheel_RR_Rims_0.geometry} material={materials.Rims} />
        <mesh geometry={nodes.Wheel_RR_Tire_Treads_0.geometry} material={materials.Tire_Treads} />
        <mesh geometry={nodes.Wheel_RR_Tire_Sidewall_0.geometry} material={materials.Tire_Sidewall} />
      </group>
      <group position={[-110,-18,-170]}  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Wheel_FR_Rims_Disc_0.geometry} material={materials.Rims_Disc} />
        <mesh geometry={nodes.Wheel_FR_Rims_0.geometry} material={materials.Rims} />
        <mesh geometry={nodes.Wheel_FR_Tire_Treads_0.geometry} material={materials.Tire_Treads} />
        <mesh geometry={nodes.Wheel_FR_Tire_Sidewall_0.geometry} material={materials.Tire_Sidewall} />
      </group>
      <group position={[110,-18,-170]}  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.Wheel_FL_Rims_Disc_0.geometry} material={materials.Rims_Disc} />
        <mesh geometry={nodes.Wheel_FL_Rims_0.geometry} material={materials.Rims} />
        <mesh geometry={nodes.Wheel_FL_Tire_Treads_0.geometry} material={materials.Tire_Treads} />
        <mesh geometry={nodes.Wheel_FL_Tire_Sidewall_0.geometry} material={materials.Tire_Sidewall} />
      </group>
      <group  rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <group position={[-1.006, -0.772, 0.212]}>
          <mesh geometry={nodes.Door_Right_Body_2_0.geometry} material={materials.Body_2} />
          <mesh geometry={nodes.Door_Right_Body_1_0.geometry} material={materials.Body_1} />
          <mesh geometry={nodes.Door_Right_Body_4_0.geometry} material={materials.Body_4} />
          <mesh geometry={nodes.Door_Right_Interior_0.geometry} material={materials.Interior} />
          <mesh geometry={nodes.Door_Right_Glass_0.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Door_Right_Side_Mirror_0.geometry} material={materials.Side_Mirror} />
        </group>
        <group position={[1.024, -0.772, 0.212]}>
          <mesh geometry={nodes.Door_Left_Side_Mirror_0.geometry} material={materials.Side_Mirror} />
          <mesh geometry={nodes.Door_Left_Body_1_0.geometry} material={materials.Body_1} />
          <mesh geometry={nodes.Door_Left_Body_2_0.geometry} material={materials.Body_2} />
          <mesh geometry={nodes.Door_Left_Interior_0.geometry} material={materials.Interior} />
          <mesh geometry={nodes.Door_Left_Body_4_0.geometry} material={materials.Body_4} />
          <mesh geometry={nodes.Door_Left_Glass_0.geometry} material={materials.Glass} />
        </group>
        <mesh geometry={nodes.Body_Body_4_0.geometry} material={materials.Body_4} />
        <mesh geometry={nodes.Body_Body_2_0.geometry} material={materials.Body_2} />
        <mesh geometry={nodes.Body_Interior_0.geometry} material={materials.Interior} />
        <mesh geometry={nodes.Body_Grills_0.geometry} material={materials.Grills} />
        <mesh geometry={nodes.Body_Body_3_0.geometry} material={materials.Body_3} />
        <mesh geometry={nodes.Body_Roof_Back_0.geometry} material={materials.Roof_Back} />
        <mesh geometry={nodes.Body_Body_1_0.geometry} material={materials.Body_1} />
        <mesh geometry={nodes.Body_Glass_0.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Body_Exhaust_Pipes_0.geometry} material={materials.Exhaust_Pipes} />
        <mesh geometry={nodes.Body_Mirror_0.geometry} material={materials.Mirror} />
        <mesh geometry={nodes.Body_SpeedOMeter_0.geometry} material={materials.SpeedOMeter} />
        <mesh geometry={nodes.Body_HeadLights_Glass_0.geometry} material={materials.HeadLights_Glass} />
        <mesh geometry={nodes.Body_HeadLights_2_0.geometry} material={materials.HeadLights_2} />
        <mesh geometry={nodes.Body_HeadLights_1_0.geometry} material={materials.HeadLights_1} />
        <mesh geometry={nodes.Body_Indicator_0.geometry} material={materials.Indicator} />
        <mesh geometry={nodes.Body_TailLights_2_0.geometry} material={materials.TailLights_2} />
        <mesh geometry={nodes.Body_TailLights_1_0.geometry} material={materials.TailLights_1} />
        <mesh geometry={nodes.Body_Reverse_Lights_0.geometry} material={materials.Reverse_Lights} />
        <mesh geometry={nodes.Body_TailLights_Glass_0.geometry} material={materials.TailLights_Glass} />
        <mesh geometry={nodes.Steering_Steering_0.geometry} material={materials.Steering} position={[0.438, -0.473, 0.21]} />
      </group>
    </group>
  )
}

useGLTF.preload('/sportscar.gltf')
